In [8]:
import numpy as np
a = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [14]:
import pandas as pd
import sklearn.datasets as datasets


In [12]:
df = pd.ModelFrame(datasets.load_iris())
df.head()


AttributeError: 'module' object has no attribute 'ModelFrame'