In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_table("wine.data", header = None, delimiter = ",")

In [6]:
df.head(120)

0      1     2     3     4    5     6     7     8     9          10  \
0     1  13.05  1.65  2.55  18.0   98  2.45  2.43  0.29  1.44   4.250000   
1     2  12.08  1.13  2.51  24.0   78  2.00  1.58  0.40  1.40   2.200000   
2     1  14.39  1.87  2.45  14.6   96  2.50  2.52  0.30  1.98   5.250000   
3     1  14.30  1.92  2.72  20.0  120  2.80  3.14  0.33  1.97   6.200000   
4     1  14.12  1.48  2.32  16.8   95  2.20  2.43  0.26  1.57   5.000000   
5     3  13.36  2.56  2.35  20.0   89  1.40  0.50  0.37  0.64   5.600000   
6     2  12.08  1.33  2.30  23.6   70  2.20  1.59  0.42  1.38   1.740000   
7     2  13.34  0.94  2.36  17.0  110  2.53  1.30  0.55  0.42   3.170000   
8     1  13.75  1.73  2.41  16.0   89  2.60  2.76  0.29  1.81   5.600000   
9     2  12.67  0.98  2.24  18.0   99  2.20  1.94  0.30  1.46   2.620000   
10    1  13.28  1.64  2.84  15.5  110  2.60  2.68  0.34  1.36   4.600000   
11    2  11.03  1.51  2.20  21.5   85  2.46  2.17  0.52  2.01   1.900000   
12    3  13.40  4.60  2.86  25.0  112  1.98  0.96  0.27  1.11   8.500000   
13    2  11.96  1.09  2.30  21.0  101  3.38  2.14  0.13  1.65   3.210000   
14    3  12.77  2.39  2.28  19.5   86  1.39  0.51  0.48  0.64   9.899999   
15    2  12.08  1.39  2.50  22.5   84  2.56  2.29  0.43  1.04   2.900000   
16    1  13.82  1.75  2.42  14.0  111  3.88  3.74  0.32  1.87   7.050000   
17    2  11.84  0.89  2.58  18.0   94  2.20  2.21  0.22  2.35   3.050000   
18    3  13.58  2.58  2.69  24.5  105  1.55  0.84  0.39  1.54   8.660000   
19    1  13.88  1.89  2.59  15.0  101  3.25  3.56  0.17  1.70   5.430000   
20    2  11.41  0.74  2.50  21.0   88  2.48  2.01  0.42  1.44   3.080000   
21    3  12.79  2.67  2.48  22.0  112  1.48  1.36  0.24  1.26  10.800000   
22    3  13.08  3.90  2.36  21.5  113  1.41  1.39  0.34  1.14   9.400000   
23    1  13.05  1.73  2.04  12.4   92  2.72  3.27  0.17  2.91   7.200000   
24    1  13.51  1.80  2.65  19.0  110  2.35  2.53  0.29  1.54   4.200000   
25    1  14.02  1.68  2.21  16.0   96  2.65  2.33  0.26  1.98   4.700000   
26    3  13.84  4.12  2.38  19.5   89  1.80  0.83  0.48  1.56   9.010000   
27    2  11.79  2.13  2.78  28.5   92  2.13  2.24  0.58  1.76   3.000000   
28    1  14.10  2.02  2.40  18.8  103  2.75  2.92  0.32  2.38   6.200000   
29    3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.200000   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...        ...   
90    1  13.87  1.90  2.80  19.4  107  2.95  2.97  0.37  1.76   4.500000   
91    2  12.29  1.41  1.98  16.0   85  2.55  2.50  0.29  1.77   2.900000   
92    2  12.29  3.17  2.21  18.0   88  2.85  2.99  0.45  2.81   2.300000   
93    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.320000   
94    3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.300000   
95    3  12.58  1.29  2.10  20.0  103  1.48  0.58  0.53  1.40   7.600000   
96    1  14.10  2.16  2.30  18.0  105  2.95  3.32  0.22  2.38   5.750000   
97    2  12.47  1.52  2.20  19.0  162  2.50  2.27  0.32  3.28   2.600000   
98    3  13.48  1.67  2.64  22.5   89  2.60  1.10  0.52  2.29  11.750000   
99    3  12.96  3.45  2.35  18.5  106  1.39  0.70  0.40  0.94   5.280000   
100   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.700000   
101   2  12.60  1.34  1.90  18.5   88  1.45  1.36  0.29  1.35   2.450000   
102   3  12.86  1.35  2.32  18.0  122  1.51  1.25  0.21  0.94   4.100000   
103   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.680000   
104   1  13.77  1.90  2.68  17.1  115  3.00  2.79  0.39  1.68   6.300000   
105   2  12.70  3.87  2.40  23.0  101  2.83  2.55  0.43  1.95   2.570000   
106   1  14.38  1.87  2.38  12.0  102  3.30  3.64  0.29  2.96   7.500000   
107   2  12.00  3.43  2.00  19.0   87  2.00  1.64  0.37  1.87   1.280000   
108   2  12.37  1.13  2.16  19.0   87  3.50  3.10  0.19  1.87   4.450000   
109   2  12.37  1.63  2.30  24.5   88  2.22  2.45  0.40  1.90   2.120000   
110   2  11.61  1.35  2.70  20.0   94  2.74  2.92  0.

In [5]:
Y = np.asarray(df[0])
print(Y[0:10])

[1 2 1 1 1 3 2 2 1 2]


In [7]:
del df[0]
df.head()

1     2     3     4    5     6     7     8     9     10    11    12  \
0  13.05  1.65  2.55  18.0   98  2.45  2.43  0.29  1.44  4.25  1.12  2.51   
1  12.08  1.13  2.51  24.0   78  2.00  1.58  0.40  1.40  2.20  1.31  2.72   
2  14.39  1.87  2.45  14.6   96  2.50  2.52  0.30  1.98  5.25  1.02  3.58   
3  14.30  1.92  2.72  20.0  120  2.80  3.14  0.33  1.97  6.20  1.07  2.65   
4  14.12  1.48  2.32  16.8   95  2.20  2.43  0.26  1.57  5.00  1.17  2.82   

     13  
0  1105  
1   630  
2  1290  
3  1280  
4  1280

In [10]:
X = np.asmatrix(df)

In [11]:
means = [0] 
stds = [1]
for i in range(13):
    means.append(np.mean(X[:,i]))
    stds.append(np.std(X[:,i]))
    X[:,i] = (X[:,i] - means[-1])/stds[-1]
    
print(means)
print(stds)

[0, 12.9665625, 2.2882031249999999, 2.3728906250000001, 19.559374999999999, 98.75, 2.3157812500000001, 2.0436718749999998, 0.35976562499999998, 1.6270312499999999, 5.0820312421874991, 0.94653125000000005, 2.6040625000000004, 750.5859375]
[1, 0.82514907507295321, 1.0601278177607805, 0.26126839750936082, 3.1296574667805102, 13.62614674073342, 0.61879369716282462, 0.98675040465357011, 0.11952683304747673, 0.58419597441563864, 2.3777951680585701, 0.22512836399138492, 0.68892855841063083, 316.53960374611279]


In [17]:
import matplotlib.pyplot as plt
%matplotlib notebook

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_cv, Y_train, Y_cv = train_test_split(X,Y,train_size=0.8,test_size=0.2,random_state=11, stratify =Y)

In [21]:
print(np.shape(X_train))
print(np.shape(X_cv))
print(np.shape(Y_train))
print(np.shape(Y_cv))

(102, 13)
(26, 13)
(102,)
(26,)


In [22]:
COV = np.round((np.cov(np.transpose(X[:,1:]))),decimals=2)
print(COV)

[[ 1.01  0.18  0.33 -0.01 -0.3  -0.38  0.26 -0.16  0.29 -0.53 -0.35 -0.17]
 [ 0.18  1.01  0.45  0.32  0.12  0.13  0.13  0.02  0.32 -0.15  0.03  0.25]
 [ 0.33  0.45  1.01 -0.11 -0.37 -0.38  0.45 -0.21  0.13 -0.38 -0.34 -0.45]
 [-0.01  0.32 -0.11  1.01  0.16  0.17 -0.23  0.2   0.21 -0.01 -0.05  0.39]
 [-0.3   0.12 -0.37  0.16  1.01  0.86 -0.42  0.58 -0.09  0.44  0.69  0.45]
 [-0.38  0.13 -0.38  0.17  0.86  1.01 -0.51  0.63 -0.21  0.56  0.79  0.46]
 [ 0.26  0.13  0.45 -0.23 -0.42 -0.51  1.01 -0.31  0.17 -0.27 -0.45 -0.32]
 [-0.16  0.02 -0.21  0.2   0.58  0.63 -0.31  1.01 -0.04  0.31  0.49  0.33]
 [ 0.29  0.32  0.13  0.21 -0.09 -0.21  0.17 -0.04  1.01 -0.56 -0.48  0.26]
 [-0.53 -0.15 -0.38 -0.01  0.44  0.56 -0.27  0.31 -0.56  1.01  0.6   0.25]
 [-0.35  0.03 -0.34 -0.05  0.69  0.79 -0.45  0.49 -0.48  0.6   1.01  0.29]
 [-0.17  0.25 -0.45  0.39  0.45  0.46 -0.32  0.33  0.26  0.25  0.29  1.01]]


In [23]:
from sklearn.linear_model import LogisticRegression

In [25]:
model1 = LogisticRegression(tol=0.0000001,max_iter=1000000,multi_class='multinomial',n_jobs=2,verbose=5,solver='lbfgs')

In [26]:
model1.fit(X_train, Y_train)

[Parallel(n_jobs=2)]: Done   1 out of   1 | elapsed:    0.1s finished


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=1000000, multi_class='multinomial',
          n_jobs=2, penalty='l2', random_state=None, solver='lbfgs',
          tol=1e-07, verbose=5, warm_start=False)

In [28]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [29]:
accuracy_score(model1.predict(X_train),Y_train)

1.0

In [31]:
accuracy_score(model1.predict(X_cv),Y_cv)

1.0

In [32]:
confusion_matrix(model1.predict(X_train),Y_train)

array([[34,  0,  0],
       [ 0, 41,  0],
       [ 0,  0, 27]])

In [33]:
confusion_matrix(model1.predict(X_cv),Y_cv)

array([[ 9,  0,  0],
       [ 0, 10,  0],
       [ 0,  0,  7]])

In [34]:
X_cv2, X_cv3, Y_cv2, Y_cv3 = train_test_split(X,Y,train_size=0.5,test_size=0.5,random_state=142)

In [36]:
print(accuracy_score(model1.predict(X_cv2),Y_cv2))
print(confusion_matrix(model1.predict(X_cv2),Y_cv2))
print(accuracy_score(model1.predict(X_cv3),Y_cv3))
print(confusion_matrix(model1.predict(X_cv3),Y_cv3))

1.0
[[23  0  0]
 [ 0 23  0]
 [ 0  0 18]]
1.0
[[20  0  0]
 [ 0 28  0]
 [ 0  0 16]]
